spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: include73
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
logging.level:
  org.hibernate.SQL: debug
